# This is a comment
FROM littlemole/reproweb_gpp_libevent_make
MAINTAINER me <little.mole@oha7.org>

ARG CXX=g++
ENV CXX=${CXX}

ARG BACKEND=
ENV BACKEND=${BACKEND}

ARG BUILDCHAIN=make
ENV BUILDCHAIN=${BUILDCHAIN}

ADD docker/run.sh /usr/local/bin/run.sh

ENV TARGET=reproweb_gpp_libevent_make

CMD /usr/local/bin/run.sh