version: '2'
services:
  web:
    build: 
      context: ./chat
      dockerfile: Dockerfile
      args:
        TS: ${TS}
        CXX: ${CXX}
        BACKEND: ${BACKEND}
        BUILDCHAIN: ${BUILDCHAIN}
    ports:
     - "9876:9876"
  user:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
      args:
        TS: ${TS}
        CXX: ${CXX}
        BACKEND: ${BACKEND}
        BUILDCHAIN: ${BUILDCHAIN}
    ports:
     - "9877:9877"
  session:
    build: 
      context: ./session-service
      dockerfile: Dockerfile
      args:
        TS: ${TS}
        CXX: ${CXX}
        BACKEND: ${BACKEND}
        BUILDCHAIN: ${BUILDCHAIN}
    ports:
     - "9878:9878"          
  redis:
    image: "redis:alpine"
  mysql:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes 
      