version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        TS: ${TS}
        CXX: ${CXX}
        BACKEND: ${BACKEND}
        BUILDCHAIN: ${BUILDCHAIN}
    ports:
     - "9876:9876"
    