<div class="side">
     <h2><!--#i18n key="login.menu.title" --></h2>
  
	 <!-- Navigation Bar -->
     <div class="navbar">

      <ul class="nav">
       <li>
            <a href="/"><!--#i18n key="login.menu.home" --></a>
       </li>
       <li>
            <a href="/login"><!--#i18n key="login.menu.login" --></a>
       </li>
       <li>
            <a href="/register"><!--#i18n key="login.menu.register" --></a>
        </li>
        <li>
            <a href="/logout"><!--#i18n key="login.menu.logout" --></a>
        </li>
        </ul>
    
    </div>      
</div>
