<div class="header">
  <b><!--#i18n key="generic.header.headline" --></b>
  <span><!--#i18n key="generic.header.headline.desc" --></span>
  <a href="https://github.com/littlemole/repro-web"><!--#i18n key="generic.header.headline.home" --></a>
  <a href="https://github.com/littlemole/repro-web/tree/master/example"><!--#i18n key="generic.header.headline.examples" --></a>
  <a href="https://github.com/littlemole/repro-web/tree/master/example/hello_ws"><!--#i18n key="generic.header.headline.this.example" --></a>
</div>